name: Add issue to infra-board

on:
  issues:
    types:
      - opened

jobs:
  add-to-project:
    if: github.repository_owner == 'ijug-ev'
    name: Add issue to infra-board
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v1.0.2
        with:
          project-url: https://github.com/orgs/ijug-ev/projects/1
          github-token: ${{ secrets.ADD_TO_PROJECT_TOKEN }}
